---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: weight-watcher-ingress
  namespace: weight-watcher-ingress
spec:
  ingressClassName: my-traefik
  rules:
  - host: ww.paas.lsedlar.cz
    http:
      paths:
      - backend:
          service:
            name: weight-watcher-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ww.paas.lsedlar.cz
    secretName: weight-watcher-cert
