---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: receiver
  name: receiver-in-lan
  namespace: weather-station
spec:
  ports:
  - name: web
    nodePort: 30171
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: receiver
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: receiver
  name: receiver-in-cluster
  namespace: weather-station
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: receiver
  type: ClusterIP
