---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-secret
  namespace: grafana
spec:
  encryptedData:
    SMTP_PASSWORD: AgBq1Bm+4tuSXqUkL4OcB3NJ11RW6d+2SZERnYKZmRm6OYjCWsPrr8biTzTsXA8SKNlLl1T87nOCmvwwjKnG94Hm1K+UjF+jVwmb3UuTHLBIi0FBAe5NaaKuKiLVDG8/90jPzgxCetDd+y6HYhMrubWLXEuHDtOR0x3XrtCAbCNzHNQosMxEC9LOcFNLtp6ZArVTn6NweA6RIEpq2YMAKKqItsQ8+SbASX8kfgKUcReTZpYFv3BlZVdAkJvcqrIdQqcxWE3O3UIGVGkW8N4MdUFoeEhJUM7wrlsc4+SCxHvzFZZ9R1B34FCJdC+0dh0YjkoIWl3SldbsEgvQovBaiUDGYc3F6MER/P/3lpQS2/RnTlSKdMjn+bEJRKWzqN3Zu943/+oOl6549Cifo3moWL6RTtKbamz8IFwectcIa1Xf9MiMzkoKC0XVffa/HkR9MyV3I4ZmBmSXp8FyoZ2rRnYVYu4AcDS+wb5YarDtjGa6efTa4f/oXzsS+svoiERK5iujcOCthJjbpME9m99ScCxxk7V+b1PDdiB7obHLjGdjfuOKIyR7Rh8pDdGgxjKIUVMMiTtkgo2EElnaHE7+XKYaINpxGwLAdHqIHphs7TItflGwgXXYy3C8lBgLsaHYulRbt2w88EtYXIWrkFPno+Teevj+kmWgU/MtFpYceknAGmnP31IJmN28XsFOmzbzSQX5Us510RFHgXIgzCTsCbjb
    SMTP_USER: AgDOauHCAkFKl2pnzdhlQOdikzxHIGLFBB/m9PwzF1qfqxRWoMsmdu4qOdZgSuAebebPo6UJoT/dGUJpH26m69risGFZrBNccR9K4D8IDIjqzYB6XrKuZQh1PhdWE0TOrbdFVsnmegt+2bufPDBC2+8ohoVmUwa2YUfZQs7tF297zdSj2hS4t2FrAE0eo+1TpGb++/suUh5DfClGAISEP695ruNEIaXFKGlgxPcnBAnsnOEwSlf9bVcLh3DKJy2M9KZXnHZp9u67n+v4tcXpKSJ0ihipUPrjQjjVNPALp70aCUCzINRfQ4gmFBdxDPs9GdO1YRC9YFcg7hIckhbP/tuLFoOJU/VlsLTNOJTYo6gF3cXT4BNYLUqVsV8mtYAB0MBT5EtF+YRfbE+qT9/v4aEGa9pbCGazqh5Qn86K8YOQ9MZimqgIri/mXf61Rg+pmLWp7IUd0f+3wubtsGJYsw/D/uW/BQwdHRtDwRTcvBcYysnAlLTjPW7aHyYhbMjSL4WbBf4IQLucwDM3le1z/BvVpYkZPdnNFk5R4lZV9e/He6hvi9LvuZVKsfrmpQ0+MhjNfgj6hJ/sk/qruozXBZ80iT7XuW2DYNqwk6FmXdOaEp/Sxvms8UxXRy9FU7NheoRvcYBddW4jCD5RlKGzJrAKzU5svJHeJcRZjFnSwpAeUc2I+vYr0cVkj8wwgZo4W8qRTp6D5P8SEgn6BMo7UcUKgrvDSkusF9c=
  template:
    metadata:
      name: grafana-smtp-secret
      namespace: grafana
